### ISSUE TITLE
get peak memory

### ISSUE THREAD

**Issue by h-jia** [ruipeterpan/torch_profiler#1]
Thanks for the great repo. I have tested with example and works great. Could you please let me know how to get the memory?

Specifically, activation memory; weight memory, and sum of peak memory if possible.

Thanks!

**Comment by ruipeterpan** [comment]
Hi! Thanks for checking this out and I'm so sorry for the late response. Currently, this profiler does not support logging detailed memory information. However, here are a few things that (I think) could help with your use case:

- Checking out Nvidia profilers/utilities like `nvidia-smi`, [DLProf](https://docs.nvidia.com/deeplearning/frameworks/dlprof-user-guide/index.html), [NSight Systems](https://developer.nvidia.com/nsight-systems), etc. In the past, to get the peak memory usage, I had written simple scripts that used `nvidia-smi `to query the GPU memory usage in ms intervals.
- For the weights memory, this repo (`torch_profiler`) allows you to check the total number of parameters in a model. If you know the data type used by your model (e.g. assuming `float32` -> 4 bytes/parameter), you can manually estimate the storage needed for the model parameters.
- Finally, if you are working with LLMs, feel free to check out [this repo](https://github.com/RahulSChand/gpu_poor) for estimating the memory consumption.

If you have any other questions/comments, feel free to let me know!

**Comment by h-jia** [comment]
Thanks!
